parser: babel-eslint
extends: airbnb
parserOptions:
  ecmaVersion: 2017
rules:
  prefer-destructuring: ["off"]
  no-underscore-dangle: ["off"]
  no-continue: ["off"]
  indent: ["error", 2, { "MemberExpression": 0 }]
  max-len: ["warn", 125]
  brace-style: ["error", "stroustrup"]
  comma-dangle: [2, 'never']
  no-plusplus: 0
  no-param-reassign: 0
  no-console: 0
  no-mixed-operators: 0
  consistent-return: 0
